---
version: 2.1

executors:
  # Whenever the Go version is updated here, .travis.yml and .promu.yml
  # should also be updated.
  golang:
    docker:
    - image: circleci/golang:1.12
    parameters:
      working_dir:
        type: string
        default: ~/project
    working_directory: << parameters.working_dir >>

jobs:
  test:
    executor: golang

    steps:
    - checkout
    - run: sudo apt-get -y install build-essential libsnmp-dev
    - run: make promu
    - run: make
    - run: git diff --exit-code
    - store_artifacts:
        path: snmp_exporter
        destination: /build/snmp_exporter
    - run: rm -v snmp_exporter

  build:
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/prometheus/snmp_exporter

    steps:
    - checkout
    - run: make promu
    - run: promu crossbuild -v
    - persist_to_workspace:
        root: .
        paths:
        - .build
    - store_artifacts:
        path: .build
        destination: /build

  generator:
    executor:
      name: golang
      working_dir: ~/project/generator

    environment:
      MIBDIRS: mibs
    steps:
    - checkout:
        path: ~/project
    - run: sudo apt-get -y install build-essential diffutils libsnmp-dev
    - run: make mibs
    - run: make generator
    - run: make parse_errors
    - run: make generate
    - run: diff -u ../snmp.yml snmp.yml

  docker_hub_master:
    executor: golang

    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run: ln -s .build/linux-amd64/snmp_exporter snmp_exporter
    - run: make docker
    - run: make docker DOCKER_REPO=quay.io/prometheus
    - run: make -C generator docker
    - run: make -C generator docker DOCKER_REPO=quay.io/prometheus
    - run: docker images
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - run: docker login -u $QUAY_LOGIN -p $QUAY_PASSWORD quay.io
    - run: make docker-publish
    - run: make docker-publish DOCKER_REPO=quay.io/prometheus
    - run: make -C generator docker-publish
    - run: make -C generator docker-publish DOCKER_REPO=quay.io/prometheus

  docker_hub_release_tags:
    executor: golang

    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run: make promu
    - run: promu crossbuild tarballs
    - run: promu checksum .tarballs
    - run: promu release .tarballs
    - store_artifacts:
        path: .tarballs
        destination: releases
    - run: ln -s .build/linux-amd64/snmp_exporter snmp_exporter
    - run: ln -s .build/linux-amd64/promtool promtool
    - run: make docker DOCKER_IMAGE_TAG=$CIRCLE_TAG
    - run: make docker DOCKER_IMAGE_TAG=$CIRCLE_TAG DOCKER_REPO=quay.io/prometheus
    - run: make -C generator docker DOCKER_IMAGE_TAG=$CIRCLE_TAG
    - run: make -C generator docker DOCKER_IMAGE_TAG=$CIRCLE_TAG DOCKER_REPO=quay.io/prometheus
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - run: docker login -u $QUAY_LOGIN -p $QUAY_PASSWORD quay.io
    - run: |
        if [[ "$CIRCLE_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
          make docker-tag-latest DOCKER_IMAGE_TAG="$CIRCLE_TAG"
          make docker-tag-latest DOCKER_IMAGE_TAG="$CIRCLE_TAG" DOCKER_REPO=quay.io/prometheus
          make docker-publish DOCKER_IMAGE_TAG="latest"
          make docker-publish DOCKER_IMAGE_TAG="latest" DOCKER_REPO=quay.io/prometheus
          make -C generator docker-tag-latest DOCKER_IMAGE_TAG="$CIRCLE_TAG"
          make -C generator docker-tag-latest DOCKER_IMAGE_TAG="$CIRCLE_TAG" DOCKER_REPO=quay.io/prometheus
        fi
    - run: make docker-publish DOCKER_IMAGE_TAG="$CIRCLE_TAG"
    - run: make docker-publish DOCKER_REPO=quay.io/prometheus DOCKER_IMAGE_TAG="$CIRCLE_TAG"
    - run: make -C generator docker-publish
    - run: make -C generator docker-publish DOCKER_REPO=quay.io/prometheus

workflows:
  version: 2
  snmp_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        filters:
          tags:
            only: /.*/
    - generator:
        filters:
          tags:
            only: /.*/
    - docker_hub_master:
        context: org-context
        requires:
        - test
        - build
        - generator
        filters:
          branches:
            only: master
    - docker_hub_release_tags:
        context: org-context
        requires:
        - test
        - build
        - generator
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
